version: "3.9"

services:
  database:
    image: postgres
    container_name: database_desafio
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=desafio
      - POSTGRES_PASSWORD=desafio
      - POSTGRES_DB=desafio
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: desafio
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local
